### PR TITLE
Start adding stuff

### PR DESCRIPTION
**Pull request by Oddant1**
Starting to flesh out the dev-docs.

### CODE REVIEW

**Comment by Oddant1** [comment]
Most of what is added as of this comment is skeleton. We may not need all of those Sphinx extensions. I was having issues getting the `automodule` and all that to work in the usage and cache docs.

**Comment by Oddant1** [comment]
@lizgehret review this because @ebolyen won't give me permission to actually request a review the right way D:<

**Comment by ebolyen** [comment]
Fun-fact: even I don't have write access to this repo
image

**Comment by lizgehret** [comment]
@gregcaporaso looks like we all need write access in order to make any changes/additions within the `developing-with-qiime2` repo. Whenever you have a minute to update our permissions - but mainly just a head's up!

**Comment by lizgehret** [comment]
Overall, stuff seems reasonable to me @Oddant1 - gonna pull this down locally and render to see what things look like.

**Comment by lizgehret** [comment]
I wasn't able to build the book locally until removing all of the q2doc sphinx extensions under the `_config.yml` file - everything looked fine otherwise, so I'm wondering if we even need those extensions.

**Review by gregcaporaso — APPROVED** [review]
Got the build working. This is now ready for merge. Thanks again @Oddant1!

**Pull request merged**
